### Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.4'

In [3]:
l = [i for i in range(10)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
l[4]

4

### Array

In [5]:
import array

In [6]:
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Numpy.array

In [7]:
n = np.array([i for i in range(10)])
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
n.dtype

dtype('int32')

In [9]:
n[5] = 4.4
print(n)
n.dtype

[0 1 2 3 4 4 6 7 8 9]


dtype('int32')

In [10]:
n2 = np.array([1,2,3,4.5])
n2.dtype

dtype('float64')

In [11]:
n = np.zeros(10)
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
n = np.zeros(10,dtype = int)
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros(shape = (3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(2)

array([1., 1.])

In [16]:
np.full(shape = (3,5),fill_value = 123)

array([[123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123]])

### Numpy.arange

In [17]:
[i for i in range(0,10,2)]

[0, 2, 4, 6, 8]

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
#[i for i in range(0,10,0.2)]

In [20]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### linspace

In [21]:
np.linspace(0,20,10) #等分

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

### random

In [22]:
np.random.randint(0,10,10)

array([1, 9, 8, 6, 1, 1, 2, 0, 5, 9])

In [23]:
np.random.randint(0,10,size = 10)

array([6, 9, 6, 2, 6, 8, 3, 4, 0, 5])

In [24]:
np.random.randint(0,10,size = (3,5))

array([[6, 9, 8, 4, 8],
       [2, 5, 1, 2, 7],
       [5, 0, 5, 6, 6]])

In [25]:
np.random.seed(666)#随机种子
np.random.randint(0,10,size = (3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [26]:
np.random.seed(666)
np.random.randint(0,10,size = (3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [27]:
np.random.random(10) #0-1之间

array([0.73159555, 0.8578588 , 0.76741234, 0.95323137, 0.29097383,
       0.84778197, 0.3497619 , 0.92389692, 0.29489453, 0.52438061])

In [28]:
np.random.normal(10,100)#正态分布

-15.584759282610502

In [29]:
np.random.normal(0,1,(3,5))#正态分布

array([[-1.76438083, -0.94249688, -1.58045861,  0.90472662, -0.82628327],
       [ 0.82101369,  0.36712592,  1.65399586,  0.13946473, -1.21715355],
       [-0.99494737, -1.56448586, -1.62879004,  1.23174866, -0.91360034]])

### 合并操作

In [30]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [31]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [32]:
A = np.array([[1,2,3],
            [3,2,1]])

In [33]:
np.concatenate([A,A])#同维度

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [34]:
np.concatenate([A,A],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1]])

In [35]:
np.concatenate([A,x.reshape(1,-1)])

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3]])

In [36]:
np.vstack([A,x])

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3]])

### 分割

In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x1,x2,x3 = np.split(x,[3,7])
x1

array([0, 1, 2])

In [39]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
A1,A2 = np.split(A,[2])

In [41]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
A1, A2 = np.split(A,[2],axis = 1)

In [44]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [45]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [46]:
A1, A2 = np.vsplit(A,[2])

In [47]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
A1,A2 = np.hsplit(A,[2])
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [49]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
X,y = np.hsplit(data,[-1])
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [51]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [52]:
y[:,0] #向量

array([ 3,  7, 11, 15])

### numpy.array运算

In [56]:
L = np.arange(10)
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
A = L*2 
A

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Functions

In [60]:
x = np.arange(1,16).reshape((3,5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [61]:
x + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [62]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

### 矩阵运算

In [67]:
A = np.full((2,2),10)
B = np.full((2,2),10)

In [68]:
A

array([[10, 10],
       [10, 10]])

In [69]:
B

array([[10, 10],
       [10, 10]])

In [70]:
A+B

array([[20, 20],
       [20, 20]])

In [71]:
A*B

array([[100, 100],
       [100, 100]])

In [72]:
A.dot(B) #矩阵乘法 

array([[200, 200],
       [200, 200]])

In [73]:
A.T

array([[10, 10],
       [10, 10]])

### 矩阵向量运算

In [74]:
v = np.array([1,2])

In [75]:
v+A

array([[11, 12],
       [11, 12]])

In [77]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [80]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [81]:
v*A

array([[10, 20],
       [10, 20]])

In [82]:
v.dot(A)

array([30, 30])

In [83]:
A.dot(v) #自动判断行向量还是列向量

array([30, 30])

### 矩阵的逆

In [95]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [96]:
invA = np.linalg.inv(A)

In [97]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [98]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [100]:
x = np.arange(16).reshape((2,8))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [104]:
pinvX = np.linalg.pinv(x)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [106]:
x.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])

### 聚合操作

In [109]:
a = np.random.random(100)


In [111]:
sum(a)

50.49292417304279

In [113]:
np.sum(a)

50.49292417304278

In [116]:
np.max(a)

0.9885036368931196

In [118]:
a.max()

0.9885036368931196

In [121]:
a.sum()

50.49292417304278

In [124]:
X = np.arange(16).reshape((4,-1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
np.sum(X)

120

In [128]:
np.sum(X,axis = 0)

array([24, 28, 32, 36])

In [130]:
np.sum(X,axis = 1)

array([ 6, 22, 38, 54])

In [133]:
np.prod(X+1)

2004189184

In [135]:
np.mean(X)

7.5

In [137]:
np.median(X)

7.5

In [146]:
np.percentile(X,q = 25) #百分位

3.75

In [147]:
for percent in [0,25,50,75,100]:
    print(np.percentile(X,percent))

0.0
3.75
7.5
11.25
15.0


In [149]:
np.var(X)#方差

21.25

In [151]:
np.std(X)#标准差

4.6097722286464435

In [158]:
x = np.random.normal(0,1,size = 1000000)

In [159]:
np.mean(x)

0.0005359986278521268

In [160]:
np.std(x)

0.9996848438123767

### 索引

In [161]:
np.min(x)

-4.940640343720167

In [163]:
np.argmin(x) 

70960

### 排序和使用索引

In [164]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [167]:
np.random.shuffle(x)
x

array([ 5,  3,  0, 10, 14,  1,  2,  9,  4,  6,  8, 15, 13, 12,  7, 11])

In [173]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [175]:
np.random.shuffle(x)
x = x.reshape((4,4))
x

array([[ 4, 10,  7, 11],
       [ 1,  8,  3,  5],
       [12, 13,  6,  0],
       [14, 15,  2,  9]])

In [177]:
np.sort(x)

array([[ 4,  7, 10, 11],
       [ 1,  3,  5,  8],
       [ 0,  6, 12, 13],
       [ 2,  9, 14, 15]])

In [179]:
np.sort(x,axis = 0)

array([[ 1,  8,  2,  0],
       [ 4, 10,  3,  5],
       [12, 13,  6,  9],
       [14, 15,  7, 11]])

In [190]:
a = np.arange(16)
np.random.shuffle(a)
a

array([ 2, 15,  6, 11,  5,  0,  4, 13, 12,  7,  8, 10,  9,  3, 14,  1])

In [192]:
np.argsort(a) #索引数组

array([ 5, 15,  0, 13,  6,  4,  2,  9, 10, 12, 11,  3,  8,  7, 14,  1],
      dtype=int64)

In [195]:
np.partition(a,3)

array([ 0,  1,  2,  3,  4,  5,  7,  6,  8,  9, 10, 11, 12, 15, 14, 13])

In [197]:
np.argpartition(a,3)

array([ 5, 15,  0, 13,  6,  4,  9,  2, 10, 12, 11,  3,  8,  1, 14,  7],
      dtype=int64)

In [200]:
np.argsort(x,axis =1 )

array([[0, 2, 1, 3],
       [0, 2, 3, 1],
       [3, 2, 0, 1],
       [2, 3, 0, 1]], dtype=int64)

### Fancy Indexing

In [210]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [209]:
x[3]

3

In [211]:
x[3:9:2]

array([3, 5, 7])

In [213]:
ind = [3,5,8]
x[ind]

array([3, 5, 8])

In [215]:
ind = np.array([[1,2],
              [3,4]])
x[ind]

array([[1, 2],
       [3, 4]])

In [217]:
X = x.reshape((4,-1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [219]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [221]:
X[0,col]

array([1, 2, 3])

In [227]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [228]:
col = [True,False,True,True]

In [230]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array 比较

In [231]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [233]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [235]:
2*x ==24-4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [237]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [241]:
np.sum(x<6)

6

In [243]:
np.count_nonzero(x<3)

3

In [245]:
np.any(x==0)

True

In [247]:
np.all(x==0)

False

In [249]:
np.sum(X%2 ==0)

8

In [251]:
np.sum(X%2==0,axis = 1)

array([2, 2, 2, 2])

In [253]:
np.sum((x>3)&(x<10))
# &位运算符

6

In [255]:
np.sum((x%2 == 0)|(x>10))

11

In [257]:
    np.sum(~(x==0))
# ~ 非运算符

15

In [259]:
x[x<5]

array([0, 1, 2, 3, 4])

In [262]:
X[X[:,3]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])