In [2]:
import numpy as np
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris.data
y = iris.target

In [5]:
X[:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
from sklearn.model_selection import train_test_split 

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2)

### StandardScaler

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
standardScaler = StandardScaler()

In [11]:
standardScaler.fit(X_train)

StandardScaler()

In [12]:
standardScaler.mean_

array([5.80833333, 3.07583333, 3.68916667, 1.1825    ])

In [15]:
standardScaler.scale_

array([0.84296929, 0.42426325, 1.79679325, 0.78407722])

In [17]:
X_train = standardScaler.transform(X_train)

In [18]:
X_train[:10,:]

array([[ 2.48130827,  1.70688049,  1.50870632,  1.0426269 ],
       [ 0.34599916, -1.12155209,  1.06346867,  0.27739615],
       [-0.72165539,  0.99977235, -1.21837427, -1.25306536],
       [-1.19616853, -0.17874123, -1.27402898, -1.1255269 ],
       [ 0.22737088, -0.88584937,  0.78519514,  0.53247307],
       [-0.12851397, -0.17874123,  0.28430279,  0.02231923],
       [ 0.8205123 , -0.65014666,  0.50692161,  0.40493461],
       [-1.19616853,  0.76406963, -0.99575545, -1.25306536],
       [-1.31479681,  0.2926642 , -1.32968369, -1.25306536],
       [ 0.58325573, -1.3572548 ,  0.67388573,  0.40493461]])

In [19]:
X_test_standard = standardScaler.transform(X_test)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [22]:
knn.score(X_test_standard,y_test)

0.9333333333333333