In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets
digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=666)

In [5]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression( max_iter=7000)
log_reg.fit(X_train,y_train)
y_log_predict = log_reg.predict(X_test)

In [6]:
from sklearn.metrics import f1_score

f1_score(y_test, y_log_predict)

0.9176470588235294

In [7]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_log_predict)

array([[404,   1],
       [  6,  39]], dtype=int64)

In [8]:
from sklearn.metrics import precision_score

precision_score(y_test, y_log_predict)

0.975

In [9]:
from sklearn.metrics import recall_score

recall_score(y_test, y_log_predict)

0.8666666666666667

In [10]:
log_reg.decision_function(X_test) #每个样本的score

array([-1.75478510e+01, -2.78855917e+01, -1.75009217e+01, -8.00899795e+01,
       -4.80527727e+01, -2.00552616e+01, -4.08531547e+01, -2.68276004e+01,
       -1.20868210e-01, -2.70598507e+01, -6.60870554e+01, -4.54642820e+01,
       -2.88053378e+01, -4.21349237e+01, -3.86175435e+01, -3.00131862e+01,
       -3.73099716e+01, -7.52114421e+01, -4.01039272e+01, -1.50621852e+01,
       -7.65108683e+00, -7.52492599e+01, -1.44241973e+01, -4.63414980e+01,
       -4.39268190e+00, -5.16431354e+01, -1.06120767e+01, -3.02559577e+01,
       -2.09434073e+01, -1.47887394e+01, -1.57172670e+01, -2.39892820e+01,
       -3.87295100e+01, -2.25905583e+01, -8.75274166e+00, -3.46334095e+00,
       -2.50968036e+01, -2.89286858e+01, -3.11655421e+01, -2.07057713e+01,
       -2.33790658e+01, -6.08677759e+01, -3.97212877e+01, -6.10340051e+01,
       -1.99018857e+01, -9.13881998e+00, -1.73321687e+01, -1.99785072e+01,
       -2.92070252e+01, -3.00501381e+01,  4.07630016e+00,  1.14977085e+01,
       -3.02648328e+01, -

In [12]:
log_reg.decision_function(X_test)[:10]

array([-17.54785104, -27.8855917 , -17.50092173, -80.08997951,
       -48.05277274, -20.0552616 , -40.85315471, -26.82760039,
        -0.12086821, -27.05985066])

In [13]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
decision_scores = log_reg.decision_function(X_test)

In [15]:
np.min(decision_scores)

-80.0899795128594

In [16]:
np.max(decision_scores)

20.880836607090856

In [27]:
y_predict_2 = np.array(decision_scores >=5, dtype = 'int') #改变阈值（threshold）

In [19]:
confusion_matrix(y_test,y_predict_2)

array([[405,   0],
       [ 18,  27]], dtype=int64)

In [20]:
precision_score(y_test,y_predict_2)

1.0

In [22]:
recall_score(y_test,y_predict_2)

0.6

In [25]:
y_predict_3 = np.array(decision_scores >=-5, dtype = 'int')

In [28]:
confusion_matrix(y_test,y_predict_3)

array([[393,  12],
       [  5,  40]], dtype=int64)

In [29]:
precision_score(y_test,y_predict_3)

0.7692307692307693

In [30]:
recall_score(y_test,y_predict_3)

0.8888888888888888